#pragma once

// FileExport — save bytes generated by the WebView UI through native UI.
//
// WKWebView under the juce:// resource scheme has NO download manager: a
// blob:/data: anchor click aborts with "Frame load interrupted" and leaves
// the page dead (see TESTING.md). UIs must instead send the bytes over the
// bridge ("enkerliSaveFile" in enkerli-bridge.js) and the editor calls
// enkerli::exportBytes():
//   * macOS / Linux standalone — async juce::FileChooser save dialog.
//   * iOS / iPadOS — temp file + UIActivityViewController (share sheet),
//     presented from the editor's responder chain so it works inside AUv3
//     app extensions, where document pickers are the unreliable path.
//
// The iOS implementation is ObjC++: add src/FileExport.mm to the plugin's
// sources when targeting Apple platforms (it compiles empty on macOS).

#include <juce_gui_basics/juce_gui_basics.h>

namespace enkerli
{

void exportBytes (juce::Component& anchor,
                  const juce::String& filename,
                  const juce::MemoryBlock& bytes);

#if ! JUCE_IOS
inline void exportBytes (juce::Component& anchor,
                         const juce::String& filename,
                         const juce::MemoryBlock& bytes)
{
    juce::ignoreUnused (anchor);
    auto chooser = std::make_shared<juce::FileChooser> (
        "Save " + filename,
        juce::File::getSpecialLocation (juce::File::userDesktopDirectory)
            .getChildFile (filename),
        "*" + juce::File (filename).getFileExtension());

    chooser->launchAsync (juce::FileBrowserComponent::saveMode
                              | juce::FileBrowserComponent::canSelectFiles,
                          [chooser, bytes] (const juce::FileChooser& fc)
                          {
                              const auto file = fc.getResult();
                              if (file != juce::File())
                                  file.replaceWithData (bytes.getData(), bytes.getSize());
                          });
}
#endif

} // namespace enkerli
